### PR TITLE
:construction_worker: adding travis ci

### PR DESCRIPTION
**Pull request by nothingelsematters**
+ Adding travis ci system

+ Adding codecov integration, as well. It has been tested locally with mock `src/test/kotlin/Test.kt`, so waiting for tests to appear.

### CODE REVIEW

**Comment by ShuffleZZZ** [comment]
> Maybe we want to receive notifications when build fails.
> If so, it can simply be done by
> 
> ```
> notifications:
>   email:
>     recipients:
>       - <email_1>
>         ...
>       - <email_n>
>     on_success: never
>     on_failure: always
> ```

Telegram chat notification would be enough, I believe

**Comment by komour** [comment]
> Telegram chat notification would be enough, I believe

But the point is to get necessary notifications automatically. Someone may fail the build while locally everything is nice, he receives notification and fix it immediately without any need to check status in the travis-ci.com
Also if you think that this is redundant - ok (; I stick to the "Leninist" approach here based on the title of his famous article - "Лучше меньше, да лучше"

**Comment by nothingelsematters** [comment]
> But the point is to get necessary notifications automatically. 

Notifications are being received automatically via travis ci telegram bot.

> Someone may fail the build <...>, he receives notification and fix it immediately without any need to check status in the travis-ci.com

Again, the notification is being received in a chat, and the person responsible will take care of it.

> Someone may fail the build while locally everything is nice

It is now impossible to merge a pr that doesn't build successfully. So, `develop` branch cannot fail unexpectedly. Only your new branch can fail, therefore you just can fix your own branch, it doesn't affect "stable" `develop`.

**Comment by nothingelsematters** [comment]
😞

**Comment by nothingelsematters** [comment]
I'm merging whatever it takes :poebat:.

**Pull request merged**
